### PR TITLE
add "admin dashboard" to sidebar menu(mobile menu)

### PR DESCRIPTION
**Pull request by uandreew**
I added a dashboard that is accessible from a computer, but for some reason was not available from the mobile version.
image

### CODE REVIEW

**Comment by uandreew** [comment]
I apologize for the unnecessary changes I made to my repository. (package.json and other)

I'm still learning how to use git.

**Comment by uandreew** [comment]
I wanted to add the patch from PR #205 to my instance, but accidentally added it to this PR. Please delete the last commit if necessary.

**Comment by Cl0v1s** [comment]
Thanks for your work ! I'll take care of this tomorow

**Comment by Cl0v1s** [comment]
To only push some files, you can choose which files to add to your commit with the `git add <your-file>` command :)

**Pull request merged**
