### PR TITLE
[FIX] Fix Akkoma V1 endpoints + falsy endorsment endpoint

### PR DESCRIPTION
**Pull request by uandreew**
akkoma changed the url a bit after the last update. So here's a fix with the changed links.

The only thing I noticed is that maybe it's just me. I don't get the text colors changing. in developers tools it gives me this error.

image

This is what an error looks like:

image

#195

### CODE REVIEW

**Comment by uandreew** [comment]
I also remembered that "/api/v1/pleroma/accounts/#USER_ID/endorsements" (previously: /api/pleroma/accounts/#USER_ID/endorsements) is not working, it was responsible for the "verified user" checkbox in the profile.

**Comment by uandreew** [comment]
#195

**Comment by uandreew** [comment]
image

As for the error, it's most likely related to this, I'll try to fix it and add a commit here.

**Comment by uandreew** [comment]
> The only thing I noticed is that maybe it's just me. I don't get the text colors changing. in developers tools it gives me this error.

In short, if you have the same error as me, either look for a fix or restore the old look to these files, after which the interface will work fine.

https://akkoma.dev/AkkomaGang/akkoma/commit/336d06b2a8ca75362578b1d67ea1f32a45c8edd3

**Comment by uandreew** [comment]
I found a way to fix api/pleroma/accounts/user_id/endorsements, now I'll upload the commit

**Comment by Cl0v1s** [comment]
Thanks for your work ! To sum up, there is still an issue about this new strict content policy ?

**Comment by uandreew** [comment]
> Thanks for your work ! To sum up, there is still an issue about this new strict content policy ?

Yes, the "new strict content policy" does not allow you to change the theme in any way. It breaks the interface. (Before that, there was a problem with the API, but it was solved)
For now, since there is no other solution, I just removed the "new strict content policy" on my instance.

**Comment by Cl0v1s** [comment]
I see, instead of changing Akkoma's code I suggest you to try to override the headers sent by your http server if applicable 

https://serverfault.com/questions/953215/how-to-force-nginx-to-override-header

I'll try and see if that works on bdx.town configuration :)

**Pull request merged**
