### PR TITLE
feat: improve bulgarian translation

### PR DESCRIPTION
**Pull request by salif**

### CODE REVIEW

**Comment by salif** [comment]
@Cl0v1s, hi I updated the Bulgarian translation, please merge.

**Comment by Cl0v1s** [comment]
Hi ! Thanks for your work, i'll look at it :)

It will be featured in the next release !

**Comment by Cl0v1s** [comment]
After retargeting to the next release branch, there is some conflicts. I could fix them but since I do not speak your language...
Could you take a look please ? Thanks a lot !

**Comment by salif** [comment]
I fixed them

**Comment by Cl0v1s** [comment]
Thanks a lot !

**Pull request merged**
