### PR TITLE
[ADD] Redirect LDAP users to a third party registration page on visitor's landing page

### PR DESCRIPTION
**Pull request by muppeth**
Added possibility to redirect users to third party registration page. 
In case user account registration is provided by third party service (eg. LDAP) you could redirect new potential users to a URL where they could create account.
In order to enable this feature, add following variables in the config:
 - `customRegProvider` "name of provider eg. your service name"
 - `customRegUrl` "URL to redirect users to create account"

### CODE REVIEW

**Comment by muppeth** [comment]
If this solution is ok with you people I will try to add missing translations for the two new strings introduced by the feature.

**Comment by Cl0v1s** [comment]
Thanks a lot ! It seems ok to me !
I'll merge this in the next release branch :)

**Comment by Cl0v1s** [comment]
Fix https://github.com/BDX-town/Mangane/issues/124

**Comment by muppeth** [comment]
Any idea when it may be? I will try to add some translations to the strings with some help of friends.

**Comment by Cl0v1s** [comment]
I think I will make more frequent releases since there is a lot of bug reports recently. They need to be fixed. 
I'm thinking this week end probably

**Pull request merged**
